// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCByAacaOUMQigs2gzWfg15uLLEuPBbLO8',
    appId: '1:482300485699:web:5cbdbab4690e8ab9f034f6',
    messagingSenderId: '482300485699',
    projectId: 'plate-1049b',
    authDomain: 'plate-1049b.firebaseapp.com',
    storageBucket: 'plate-1049b.firebasestorage.app',
    measurementId: 'G-2NSJP46S4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTZDx1zX6xZsIW7TFW6kubrNkwG21r4og',
    appId: '1:482300485699:android:5f2539adb4cfc45cf034f6',
    messagingSenderId: '482300485699',
    projectId: 'plate-1049b',
    storageBucket: 'plate-1049b.firebasestorage.app',
  );

 static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS3wRF6I29IJaNvcNBirpc1LuIRCaecB8',
    appId: '1:482300485699:ios:2d256f154a96831df034f6',
    messagingSenderId: '482300485699',
    projectId: 'plate-1049b',
    storageBucket: 'plate-1049b.firebasestorage.app',
    iosClientId: '482300485699-amj5ain5fpv0s1v4cgvi0mf52rrlpd2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.modelTest',
  ); 

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS3wRF6I29IJaNvcNBirpc1LuIRCaecB8',
    appId: '1:482300485699:ios:2d256f154a96831df034f6',
    messagingSenderId: '482300485699',
    projectId: 'plate-1049b',
    storageBucket: 'plate-1049b.firebasestorage.app',
    iosClientId: '482300485699-amj5ain5fpv0s1v4cgvi0mf52rrlpd2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.modelTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCByAacaOUMQigs2gzWfg15uLLEuPBbLO8',
    appId: '1:482300485699:web:6f5c50920be8fa81f034f6',
    messagingSenderId: '482300485699',
    projectId: 'plate-1049b',
    authDomain: 'plate-1049b.firebaseapp.com',
    storageBucket: 'plate-1049b.firebasestorage.app',
    measurementId: 'G-78WWPXKCXB',
  );
}
